# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11l7o2vtTegubtEe0ba4DdC0r79NkYnnr
"""

import pandas as pd

link = input('Enter csv link of data = ')
data = pd.read_csv(link)
df = pd.DataFrame(data)

n = df.isnull.sum().sum() #checking for null values
print('There is',n,'null values in our data')

print('Column wise null values =',df.isnull().sum())

df.duplicated()  #checking for duplicate values in our data
print('There is total',df.duplicated().sum(),'duplicates in our dataset')

df[df.duplicated()] # viewing duplicate rows
df.drop_duplicates(inplace=True)


ask = input('You want to drop rows which contain null value yes/no = ').lower() #asking user what they want with null value rows

if ask=='yes':
    df.dropna(inplace=True)
elif ask=='no':
    imp = int(input("How do you want to fill missing values? (1 = mean, 2 = median, 3 = mode)"))
    if imp==1:
        df.fillna(df.mean(),inplace=True)
    elif imp==2:
        df.fillna(df.median(),inplace=True)
    elif imp==3:
        df.fillna(df.mode(),inplace=True)
    else:
        print('Invalid choice')
else:
    print('Invalid choice')